import BaseSeeder from "@ioc:Adonis/Lucid/Seeder";
import Post from "App/Models/Post";

export default class PostSeeder extends BaseSeeder {
  public async run() {
    const uniqueKey = "slug";

    await Post.updateOrCreateMany(uniqueKey, [
      {
        userId: 1,
        slug: "in-sit-amet-velit-risus",
        title: "In sit amet velit risus",
        excerpt:
          "Suspendisse eu lorem vitae justo ullamcorper blandit. Sed sagittis ipsum id erat vestibulum, in laoreet dolor volutpat. Vivamus ac eros at lorem vulputate luctus. Etiam interdum neque eu laoreet efficitur.",
        content:
          "Suspendisse eu lorem vitae justo ullamcorper blandit. Sed sagittis ipsum id erat vestibulum, in laoreet dolor volutpat. Vivamus ac eros at lorem vulputate luctus. Etiam interdum neque eu laoreet efficitur.\n" +
          "Vivamus consectetur id sem in interdum.Fusce nisl lorem, interdum eget purus id, finibus tempus ipsum.Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse diam arcu, viverra eu luctus et, consequat eu tortor.Cras tempor mollis gravida.Proin rhoncus erat diam, id commodo urna cursus sit amet.Suspendisse placerat in metus feugiat luctus.Donec elementum mi at diam condimentum lacinia.Interdum et malesuada fames ac ante ipsum primis in faucibus.Curabitur vulputate, nisl et euismod posuere, nibh lacus pretium eros, in scelerisque erat eros nec urna.Aenean at hendrerit orci.\n" +
          "Vivamus sodales lorem at est posuere finibus. Fusce mattis dictum rhoncus. Duis sollicitudin leo non sem maximus, ac rutrum massa laoreet. Integer suscipit dictum malesuada. Nullam pellentesque, magna aliquam porta varius, sem leo scelerisque nulla, vitae dignissim est lectus vel eros. Etiam ultrices odio venenatis, dignissim lacus in, iaculis diam. Integer ultrices turpis eget auctor fermentum.\n" +
          "Interdum et malesuada fames ac ante ipsum primis in faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam maximus nisi non accumsan sollicitudin. Vestibulum id iaculis lacus, sit amet viverra elit. Mauris dapibus luctus ligula sit amet eleifend. Duis nunc est, egestas ut tellus ut, sagittis pulvinar felis. Fusce turpis ex, fermentum nec elementum in, finibus nec ipsum. Proin feugiat ut nibh quis iaculis.\n" +
          "Duis varius, leo eu faucibus pharetra, libero urna convallis quam, a bibendum nunc felis quis justo. Pellentesque scelerisque accumsan leo vel vulputate. Mauris justo metus, egestas vitae efficitur vitae, ornare quis odio. Mauris lorem lorem, semper a leo et, facilisis consequat eros. Sed tincidunt metus eleifend, hendrerit ante in, luctus arcu. Morbi nulla ex, lacinia sed risus at, dapibus ultricies massa. Praesent eget suscipit justo. Mauris eget consequat ligula. Nulla elementum nisi sit amet mi rutrum, id porttitor justo laoreet. Donec vel augue et nibh consectetur laoreet. Sed ac sem hendrerit, dictum eros in, maximus dolor. Aliquam sed felis ut dui aliquam tristique. Mauris libero diam, vestibulum a erat nec, efficitur suscipit metus. Suspendisse risus urna, venenatis nec vestibulum at, finibus sed quam. Sed pulvinar pretium arcu, rhoncus tempor metus.\n" +
          "Quisque dapibus lectus id odio dictum, in commodo erat maximus. Ut elementum fermentum scelerisque. Sed dapibus, metus vel laoreet commodo, sem tortor tincidunt tortor, quis tempor lacus odio et arcu. Proin placerat, arcu eget porta eleifend, massa nulla posuere felis, quis tempus tortor sem a justo. Morbi elementum maximus sem, at facilisis turpis tristique et. Aliquam scelerisque lorem a sem hendrerit, ut efficitur nulla vulputate. Etiam laoreet mi sed eleifend posuere.\n" +
          "Fusce non consectetur leo. Suspendisse quis sem justo. Nulla in volutpat elit. Nulla placerat velit urna, ut pellentesque purus aliquet eu. Nunc nec nibh risus. Sed aliquet condimentum mi, id maximus dui lacinia eu. Pellentesque viverra neque eget risus finibus, ac lobortis nisi dapibus. Quisque ut accumsan risus. Etiam in magna sit amet dui euismod convallis porta non elit. Ut ac vulputate lacus. Ut non ornare urna. Aenean consequat id sem vitae egestas.",
      },
      {
        userId: 1,
        slug: "lorem-ipsum-dolor-sit-amet-consectetur",
        title: "Lorem ipsum dolor sit amet, consectetur.",
        excerpt:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae magna auctor, euismod quam eu, lobortis ante. Quisque eu urna vitae ex scelerisque rutrum vitae quis libero. Nam non nulla eros.",
        content:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae magna auctor, euismod quam eu, lobortis ante. Quisque eu urna vitae ex scelerisque rutrum vitae quis libero. Nam non nulla eros.\n" +
          "Ut dictum porta eleifend. Curabitur erat quam, auctor non augue non, aliquet mollis lectus. Donec suscipit congue sagittis. Vestibulum rhoncus ultricies odio non vehicula. Praesent sapien mauris, dignissim ac suscipit aliquet, egestas ut orci. Pellentesque sodales tristique maximus. Suspendisse mattis elit ac rhoncus faucibus. Etiam gravida justo a placerat aliquet. Quisque odio ipsum, scelerisque eu odio et, interdum vulputate libero. Phasellus volutpat mollis dui, a rhoncus est molestie sit amet. Sed lacinia orci id lectus dictum malesuada.\n" +
          "Maecenas posuere suscipit molestie. Vivamus non sapien diam. Maecenas semper justo non est bibendum tristique a vitae sapien. Morbi at gravida dui. Duis accumsan odio eget ex euismod luctus. Etiam eu sapien libero. Proin in dolor non diam ullamcorper suscipit. Nulla facilisi.\n" +
          "Aenean sodales scelerisque ullamcorper. Sed et efficitur ante, sit amet pharetra lacus. Cras eu quam sed mauris ultricies posuere. Duis vel sagittis odio, nec fringilla sapien. Vestibulum pharetra posuere luctus. Sed varius maximus pharetra. Vivamus vel felis urna. Donec accumsan ullamcorper nibh, sit amet rutrum tellus. Integer et ipsum euismod, porta lectus id, congue lectus. Proin viverra, ligula eget venenatis ultrices, lectus erat aliquam nulla, vel cursus augue mauris non mi. Ut rutrum orci at ipsum efficitur ultricies. Maecenas feugiat tempor leo sit amet posuere. Suspendisse vitae odio ac lectus aliquam ullamcorper. Fusce mollis egestas malesuada.\n" +
          "Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ultrices dignissim tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rutrum maximus lobortis. Nullam et nisl sit amet augue tristique viverra. In justo nunc, hendrerit ut mi et, lacinia varius felis. Cras tellus dui, congue ut tincidunt vel, luctus in nunc. Vivamus non quam sollicitudin, imperdiet erat vitae, tincidunt augue. Praesent vitae lacinia quam. Aenean suscipit at libero sed molestie. Praesent viverra, eros sed ornare gravida, lorem quam accumsan odio, porttitor mollis ligula justo sit amet diam. Sed ac congue mauris. Quisque dignissim metus nec metus aliquam fringilla. Curabitur erat mi, ornare ac nibh et, placerat scelerisque erat. Nulla facilisi.\n" +
          "Pellentesque turpis dui, mollis et dui at, luctus suscipit erat. Sed et ultrices lacus, eu ultrices ipsum. Vestibulum ligula elit, lobortis sit amet velit ut, efficitur tincidunt ex. Praesent sed ante risus. Integer semper lectus nulla, at tempus libero venenatis in. Quisque posuere ligula sit amet ipsum laoreet pharetra. In varius nunc at mauris mollis vehicula. In eu velit in risus consectetur sollicitudin a ut sapien. Nulla scelerisque id turpis in imperdiet. Nulla vitae fringilla est. Cras id molestie lectus. Fusce elementum velit et magna venenatis posuere.\n" +
          "Sed posuere nisl felis, id fringilla nisl hendrerit vel. Curabitur vitae augue a elit dictum accumsan. Nullam rhoncus dui ut dolor consectetur ullamcorper. Nullam dui nulla, aliquet vitae erat a, luctus finibus ipsum. Fusce velit nunc, mollis id felis id, luctus commodo neque. Praesent id tincidunt orci. In elementum, est vel iaculis aliquet, magna risus ultrices sapien, ut pulvinar orci nisl accumsan sapien. Proin lobortis, tellus quis sollicitudin viverra, magna ante vehicula ipsum, ut accumsan leo risus ac ex. Aenean nunc dolor, blandit in gravida et, posuere vitae augue. Suspendisse potenti. Nulla facilisi.\n" +
          "Donec quis felis quis massa ultrices iaculis. Fusce consequat ante ut vulputate tempor. Nullam convallis leo nunc, commodo accumsan purus volutpat non. Maecenas venenatis, sapien at commodo rhoncus, felis ligula fringilla ligula, nec convallis odio dui at orci. Phasellus nec purus vel nisl hendrerit tincidunt volutpat ac velit. Nullam ut consectetur justo, ac ornare eros. Aliquam pulvinar lectus id tempor feugiat. Sed ac pulvinar metus.\n" +
          "Maecenas venenatis risus sed nisi tempor, sed suscipit tellus euismod. Praesent mattis purus nibh, vel pulvinar quam iaculis non. Curabitur nec iaculis enim. Nunc mauris nibh, fermentum vitae tristique quis, placerat in elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus sagittis dui ipsum. Sed lobortis tristique dolor quis dignissim. Etiam non ullamcorper sapien. Quisque ullamcorper in turpis sed vehicula. Nullam ac pulvinar sem.",
      },
    ]);
  }
}
